name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.13.x'

    - name: Test
      run: go test -v ./...
      
    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk Test
      run: |
        snyk test --all-projects --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    

  docker:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./app_go
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max